// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'check': string;
  'form': string;
  'input': string;
  'new_user': string;
  'or': string;
  'root': string;
  'submit': string;
  'with_google': string;
  'with_microsoft': string;
}
export const cssExports: CssExports;
export default cssExports;
