// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'check': string;
  'empty_input': string;
  'form': string;
  'input': string;
  'submit': string;
  'wrong_email': string;
  'wrong_input': string;
  'wrong_password': string;
}
export const cssExports: CssExports;
export default cssExports;
