// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'new_user': string;
  'or': string;
  'root': string;
  'with_google': string;
  'with_microsoft': string;
}
export const cssExports: CssExports;
export default cssExports;
